# =====================================================
# OAG WEB SYSTEM - PROMETHEUS CONFIGURATION
# =====================================================
# Monitoring configuration for production deployment

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OAG Web Application
  - job_name: 'oag-web'
    static_configs:
      - targets: ['oag-web:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx metrics (if nginx-prometheus-exporter is installed)
  - job_name: 'nginx'
    static_configs:
      - targets: ['oag-web:9113']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Blackbox exporter for external monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://ag.go.ke
        - https://admin.ag.go.ke
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Supabase monitoring (if metrics endpoint available)
  - job_name: 'supabase'
    static_configs:
      - targets: ['your-supabase-project.supabase.co']
    metrics_path: '/metrics'
    scheme: https
    scrape_interval: 60s
    scrape_timeout: 30s
